# Generated by Django 5.2.10 on 2026-01-20 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sales',
            name='total_amount',
            field=models.IntegerField(),
        ),
    ]
