# Generated by Django 5.2.10 on 2026-02-05 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0003_remove_store_location_sale_payment_delete_sales'),
    ]

    operations = [
        migrations.DeleteModel(
            name='login',
        ),
    ]
