# Generated by Django 5.2.10 on 2026-02-22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("management", "0005_store_created_at_loginactivity"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "role",
                    models.CharField(
                        choices=[("owner", "Owner"), ("manager", "Manager"), ("staff", "Staff")],
                        default="staff",
                        max_length=30,
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.RemoveField(
            model_name="store",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="store",
            name="store_id",
        ),
        migrations.AddField(
            model_name="store",
            name="location",
            field=models.CharField(default="", max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="store",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="stores",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.RenameModel(
            old_name="Sale",
            new_name="Sales",
        ),
        migrations.RenameField(
            model_name="sales",
            old_name="quantity_sold",
            new_name="quantity",
        ),
        migrations.RenameField(
            model_name="sales",
            old_name="store_item",
            new_name="store",
        ),
        migrations.RenameField(
            model_name="sales",
            old_name="total_price",
            new_name="price",
        ),
        migrations.RemoveField(
            model_name="sales",
            name="sold_at",
        ),
        migrations.AddField(
            model_name="sales",
            name="medicine",
            field=models.CharField(default="", max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="sales",
            name="total",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.RenameField(
            model_name="payment",
            old_name="paid_at",
            new_name="date",
        ),
        migrations.AddField(
            model_name="payment",
            name="method",
            field=models.CharField(
                choices=[("cash", "Cash"), ("card", "Card"), ("transfer", "Transfer")], default="cash", max_length=50
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="sale",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="payments", to="management.sales"
            ),
        ),
        migrations.AlterField(
            model_name="sales",
            name="quantity",
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name="sales",
            name="store",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="sales", to="management.store"
            ),
        ),
    ]
