# Generated by Django 5.2.5 on 2026-02-25 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0006_align_models_with_requested_schema'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='location',
            field=models.CharField(help_text='Physical location/address of the store', max_length=255),
        ),
        migrations.AlterField(
            model_name='store',
            name='name',
            field=models.CharField(help_text='Name of the pharmacy store', max_length=100),
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
