# Generated by Django 5.2.10 on 2026-02-25 06:18

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0007_alter_store_location_alter_store_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sales',
            options={'ordering': ['-date'], 'verbose_name': 'Sale', 'verbose_name_plural': 'Sales'},
        ),
        migrations.AlterModelOptions(
            name='store',
            options={'ordering': ['-id'], 'verbose_name': 'Store', 'verbose_name_plural': 'Stores'},
        ),
        migrations.AddField(
            model_name='sales',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Date when the sale was created'),
        ),
    ]
